name: Build the Logo!

"on":
  push:
    branches: [master, main]
  workflow_dispatch:


jobs:
  build-pdfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true

      - name: 📄 Compile the Logo
        uses: xu-cheng/latex-action@v3
        with:
          root_file: flowR.tex
          latexmk_use_lualatex: true
          extra_fonts: "Pecita.otf"

      - name: 📦 Upload the Logo
        uses: actions/upload-artifact@v4
        with:
          name: flowR
          path: build/flowR.pdf